// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/java/main/proto/ExternalService.proto

package com.kairos.interfacegrpc;

public final class ExternalService {
  private ExternalService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kairos_interfacegrpc_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kairos_interfacegrpc_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kairos_interfacegrpc_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kairos_interfacegrpc_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/java/main/proto/ExternalService.pr" +
      "oto\022\030com.kairos.interfacegrpc\"\026\n\007Request" +
      "\022\013\n\003req\030\001 \001(\t\"\027\n\010Response\022\013\n\003res\030\001 \001(\t2_" +
      "\n\007Service\022T\n\013toUpperCase\022!.com.kairos.in" +
      "terfacegrpc.Request\032\".com.kairos.interfa" +
      "cegrpc.ResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_kairos_interfacegrpc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kairos_interfacegrpc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kairos_interfacegrpc_Request_descriptor,
        new java.lang.String[] { "Req", });
    internal_static_com_kairos_interfacegrpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kairos_interfacegrpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kairos_interfacegrpc_Response_descriptor,
        new java.lang.String[] { "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
