// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/java/main/proto/ExternalService.proto

package com.kairos.interfacegrpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kairos.interfacegrpc.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string req = 1;</code>
   * @return The req.
   */
  java.lang.String getReq();
  /**
   * <code>string req = 1;</code>
   * @return The bytes for req.
   */
  com.google.protobuf.ByteString
      getReqBytes();
}
