// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/java/main/proto/ExternalService.proto

package com.kairos.interfacegrpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kairos.interfacegrpc.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string res = 1;</code>
   * @return The res.
   */
  java.lang.String getRes();
  /**
   * <code>string res = 1;</code>
   * @return The bytes for res.
   */
  com.google.protobuf.ByteString
      getResBytes();
}
