version: "3"
services:
  client:
    image: client-image
    depends_on:
      - service
    ports:
      - "8080:8080"
  service:
    image: service-image
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    links:
      - rabbitmq
  worker:
    image: worker-image
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    links:
      - rabbitmq
  external-service:
    image: external-service-image
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    links:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
volumes:
  rabbitmqdata:










#version: "3"
  #services:
    #  api:
    #build: ./api
    #ports:
    # - "3000:3000"
    #environment:
    # - RABBITMQ_HOST=rabbitmq
    #depends_on:
  # - rabbitmq
    #websocket:
    #build: ./websocket
    #ports:
    # - "8080:8080"
    #environment:
    # - RABBITMQ_HOST=rabbitmq
    #depends_on:
  # - rabbitmq
    #rabbitmq:
    #image: rabbitmq:3-management
    #ports:
    # - "5672:5672"
  # - "15672:15672"

#//


#apiVersion: apps/v1
#kind: Deployment
  #metadata:
  #name: api
  #spec:
  # replicas: 1
    #selector:
    # matchLabels:
  #  app: api
    #template:
    #metadata:
    #  labels:
    #    app: api
    #spec:
    #  containers:
    #    - name: api
    #     image: my-api:latest
  #  #     ports:
    #       - containerPort: 3000
    #     env:
    #       - name: RABBITMQ_HOST
  #         value: rabbitmq
#---
#apiVersion: v1
#kind: Service
  #metadata:
  #name: api
  #spec:
    #selector:
  #  app: api
    #ports:
    #    - name: http
    # port: 3000
  # targetPort: 3000
#---
#apiVersion: apps/v1
#kind: Deployment
  #metadata:
  # name: websocket
  #spec:
  #replicas: 1
    #selector:
    #  matchLabels:
  #  app: websocket
    #template:
    #  metadata:
    #    labels:
    #     app: websocket
    #spec:
    #  containers:
  #   - name:



#//




#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: my-app
#spec:
 # replicas: 1
  #selector:
   # matchLabels:
    #  app: my-app
  #template:
   # metadata:
    #  labels:
     #   app: my-app
    #spec:
     # containers:
      #  - name: my-app
       #   image: my-app:latest
        #  ports:
         #   - containerPort: 8080
         # env:
          #  - name: SPRING_PROFILES_ACTIVE
           #   value: prod
#---
#apiVersion: v1
#kind: Service
#metadata:
 # name: my-app
#spec:
 # selector:
  #  app: my-app
  #ports:
   # - name: http
    #  port: 80
     # targetPort: 8080


